import { WORLD_WIDTH } from '../../constants';
import generatedLevel from './berlinLevel.generated.json';
import { validateBerlinEntities } from './berlinLevelSchema';
import type { BerlinEntity, BerlinSection, GroundSegment } from './types';

export const BERLIN_SECTIONS: readonly BerlinSection[] = [
  { id: 'tutorial', label: 'APARTMENT', startX: 0, endX: 1600, artSlot: 'background.apartment' },
  { id: 'firstPit', label: 'BACK ALLEY GAP', startX: 1600, endX: 3200, artSlot: 'background.street' },
  { id: 'kiez', label: 'KIEZ STREET', startX: 3200, endX: 5000, artSlot: 'background.street' },
  { id: 'bridge', label: 'OBERBAUMBRÜCKE', startX: 5000, endX: 6800, artSlot: 'background.bridge' },
  { id: 'night', label: 'NIGHT BERLIN', startX: 6800, endX: 8500, artSlot: 'background.night' },
  { id: 'scaffold', label: 'SCAFFOLD ASCENT', startX: 8500, endX: 10300, artSlot: 'background.night' },
  { id: 'rooftops', label: 'ROOFTOPS', startX: 10300, endX: 12000, artSlot: 'background.club' },
  { id: 'finalPit', label: 'FINAL GAP', startX: 12000, endX: 13800, artSlot: 'background.club' },
  {
    id: 'finale',
    label: 'CLUB EXTERIOR',
    startX: 13800,
    endX: WORLD_WIDTH,
    artSlot: 'background.club',
  },
] as const;

export const CLUB_ENTRANCE_X = 15300;

/** One unbroken floor across the whole level: there are no pits to fall into. */
export const GROUND_SEGMENTS: readonly GroundSegment[] = [
  { id: 'ground-1', startX: 0, endX: WORLD_WIDTH },
] as const;

// Authoritative level layout, generated by the dev layout editor: press P in
// layout mode and it POSTs to /__level-editor/save, which rewrites the JSON
// below. Editing that file by hand is fine too; it is validated on import so
// a bad edit fails loudly at startup instead of producing a broken scene.
export const BERLIN_ENTITIES: readonly BerlinEntity[] = validateBerlinEntities(generatedLevel);

export function sectionIndexAtX(x: number): number {
  const index = BERLIN_SECTIONS.findIndex((section) => x >= section.startX && x < section.endX);
  return index < 0 ? BERLIN_SECTIONS.length - 1 : index;
}
