import { GROUND_Y, WORLD_WIDTH } from '../../constants';
import { CROUCHING_BODY } from './playerPhysics';
import type { BerlinEntity, BerlinSection } from './types';

export const BERLIN_SECTIONS: readonly BerlinSection[] = [
  { id: 'apartment', label: 'APARTMENT', startX: 0, endX: 800, artSlot: 'background.apartment' },
  { id: 'street', label: 'BERLIN STREET', startX: 800, endX: 2200, artSlot: 'background.street' },
  { id: 'bridge', label: 'BRIDGE', startX: 2200, endX: 3800, artSlot: 'background.bridge' },
  { id: 'night', label: 'NIGHT BERLIN', startX: 3800, endX: 5200, artSlot: 'background.night' },
  {
    id: 'club',
    label: 'CLUB EXTERIOR',
    startX: 5200,
    endX: WORLD_WIDTH,
    artSlot: 'background.club',
  },
] as const;

const groundObstacle = (
  id: string,
  x: number,
  label: string,
  artSlot: string,
  width = 84,
  height = 62,
): BerlinEntity => ({
  id,
  type: 'obstacle',
  action: 'jump',
  x,
  y: GROUND_Y - height / 2,
  width,
  height,
  label,
  artSlot,
  hitbox: {
    width: Math.max(width + 12, 74),
    height: Math.max(height + 6, 52),
    offsetX: 0,
    offsetY: height / 2 - Math.max(height + 6, 52) / 2,
  },
});

const duckObstacle = (
  id: string,
  x: number,
  label: string,
  artSlot: string,
  width: number,
  height: number,
  hitboxWidth: number,
  hitboxHeight: number,
  bottomClearance = 10,
): BerlinEntity => ({
  id,
  type: 'obstacle',
  action: 'duck',
  x,
  y: GROUND_Y - CROUCHING_BODY.height - bottomClearance - height / 2,
  width,
  height,
  label,
  artSlot,
  hitbox: {
    width: hitboxWidth,
    height: hitboxHeight,
    offsetX: 0,
    offsetY: height / 2 - hitboxHeight / 2,
  },
});

export const BERLIN_ENTITIES: readonly BerlinEntity[] = [
  {
    id: 'usb',
    type: 'collectible',
    kind: 'usb',
    label: 'USB',
    x: 650,
    y: GROUND_Y - 72,
    width: 86,
    height: 62,
    score: 500,
    mandatory: true,
    artSlot: 'collectible.usb',
  },
  groundObstacle('trash-bags', 1050, 'TRASH BAGS', 'obstacle.trash'),
  groundObstacle('scooter', 1450, 'SCOOTER', 'obstacle.scooter', 100, 55),
  {
    id: 'headphones',
    type: 'collectible',
    kind: 'headphones',
    label: 'HEADPHONES',
    x: 1750,
    y: GROUND_Y - 120,
    width: 54,
    height: 54,
    score: 200,
    artSlot: 'collectible.headphones',
  },
  groundObstacle('street-barrier', 2050, 'BARRIER', 'obstacle.barrier', 105, 68),
  duckObstacle('low-sign', 2500, 'LOW SIGN', 'obstacle.lowSign', 150, 30, 164, 34),
  {
    id: 'cyclist',
    type: 'obstacle',
    action: 'moving',
    label: 'CYCLIST',
    x: 2850,
    y: GROUND_Y - 78 / 2,
    width: 105,
    height: 78,
    hitbox: {
      width: 120,
      height: 72,
      offsetX: 0,
      offsetY: 78 / 2 - 72 / 2,
    },
    movement: { distance: 150, durationMs: 1500 },
    artSlot: 'npc.cyclist',
  },
  {
    id: 'poster',
    type: 'collectible',
    kind: 'poster',
    label: 'POSTER',
    x: 3150,
    y: GROUND_Y - 120,
    width: 50,
    height: 64,
    score: 100,
    artSlot: 'collectible.poster',
  },
  groundObstacle('broken-pavement', 3500, 'PUDDLE', 'obstacle.puddle', 130, 38),
  {
    id: 'energy',
    type: 'collectible',
    kind: 'energy',
    label: 'ENERGY',
    x: 3700,
    y: GROUND_Y - 105,
    width: 42,
    height: 66,
    score: 0,
    timeBonus: 3,
    artSlot: 'collectible.energy',
  },
  {
    id: 'wanderer',
    type: 'obstacle',
    action: 'moving',
    label: 'NIGHT WANDERER',
    x: 4000,
    y: GROUND_Y - 100 / 2,
    width: 70,
    height: 100,
    hitbox: {
      width: 76,
      height: 94,
      offsetX: 0,
      offsetY: 100 / 2 - 94 / 2,
    },
    movement: { distance: 120, durationMs: 1800 },
    artSlot: 'npc.wanderer',
  },
  {
    id: 'vinyl',
    type: 'collectible',
    kind: 'vinyl',
    label: 'VINYL',
    x: 4350,
    y: GROUND_Y - 125,
    width: 60,
    height: 60,
    score: 150,
    artSlot: 'collectible.vinyl',
  },
  duckObstacle('cable', 4700, 'HANGING CABLE', 'obstacle.cable', 160, 25, 176, 32, 12),
  groundObstacle('taxi', 5050, 'TAXI', 'obstacle.taxi', 175, 82),
  {
    id: 'pass',
    type: 'collectible',
    kind: 'pass',
    label: 'CLUB PASS',
    x: 5450,
    y: GROUND_Y - 115,
    width: 48,
    height: 66,
    score: 200,
    artSlot: 'collectible.pass',
  },
  groundObstacle('queue-barrier', 5750, 'QUEUE BARRIER', 'obstacle.queueBarrier', 115, 68),
  duckObstacle('pipe', 6100, 'LOW PIPE', 'obstacle.pipe', 160, 30, 174, 34, 11),
  groundObstacle('final-barrier', 6450, 'BARRIER', 'obstacle.barrier', 115, 72),
  {
    id: 'backstage',
    type: 'finish',
    label: 'FINISH',
    x: 6800,
    y: GROUND_Y - 120,
    width: 150,
    height: 240,
    artSlot: 'finish.backstage',
  },
] as const;

export function sectionIndexAtX(x: number): number {
  const index = BERLIN_SECTIONS.findIndex((section) => x >= section.startX && x < section.endX);
  return index < 0 ? BERLIN_SECTIONS.length - 1 : index;
}
