import Phaser from 'phaser';import {Depth,DESIGN_HEIGHT,DESIGN_WIDTH,GROUND_Y,START_TIME,WORLD_WIDTH} from '../constants';import {Player} from '../entities/Player';import {buildBerlinWorld} from '../level/berlinLevel';import {HudSystem} from '../systems/HudSystem';import {ObstacleSystem} from '../systems/ObstacleSystem';import {applyObstacle,collectUsb,initialProgress,startRun,tickTimer,tryFinish} from '../systems/gameRules';import type {BerlinProgress} from '../types/game';
export class BerlinScene extends Phaser.Scene{
 private player!:Player;private hud!:HudSystem;private progress!:BerlinProgress;private intro!:Phaser.GameObjects.Container;private keys!:Phaser.Types.Input.Keyboard.CursorKeys;private space!:Phaser.Input.Keyboard.Key;private invulnerable=false;private usb!:Phaser.GameObjects.Container;private usbZone!:Phaser.GameObjects.Zone;private finishZone!:Phaser.GameObjects.Zone;
 constructor(){super('BerlinScene')}
 create(){this.progress={...initialProgress(),seconds:START_TIME};this.physics.world.setBounds(0,0,WORLD_WIDTH,DESIGN_HEIGHT);this.cameras.main.setBounds(0,0,WORLD_WIDTH,DESIGN_HEIGHT);this.cameras.main.setBackgroundColor('#2a1742');buildBerlinWorld(this);const ground=this.add.zone(WORLD_WIDTH/2,GROUND_Y+10,WORLD_WIDTH,20);this.physics.add.existing(ground,true);this.player=new Player(this,230);this.physics.add.collider(this.player,ground);
  const obstacles=new ObstacleSystem(this);this.physics.add.overlap(this.player,obstacles.zones,()=>this.hitObstacle());this.createUsb();this.createFinish();this.hud=new HudSystem(this,()=>this.action());this.hud.update(this.progress);this.createIntro();this.keys=this.input.keyboard!.createCursorKeys();this.space=this.input.keyboard!.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE);this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{if(p.x<DESIGN_WIDTH-180||p.y<520)this.action()});this.cameras.main.startFollow(this.player,true,.1,.1,-260,0);this.cameras.main.setLerp(.08,.08);
 }
 private createIntro(){const panel=this.add.rectangle(0,0,620,310,0x0d0916,.94).setStrokeStyle(5,0xff5e3c);const text=this.add.text(0,0,'INCOMING CALL\n\nDUDE, WHERE ARE YOU?\nYOU’RE PLAYING NEXT.\n\nPRESS SPACE OR TAP TO START',{fontFamily:'Space Mono',fontSize:'25px',fontStyle:'bold',color:'#fff',align:'center',lineSpacing:8}).setOrigin(.5);this.intro=this.add.container(DESIGN_WIDTH/2,DESIGN_HEIGHT/2,[panel,text]).setScrollFactor(0).setDepth(Depth.UI);}
 private createUsb(){const body=this.add.rectangle(0,0,62,26,0xededed).setStrokeStyle(3,0x18111e);const plug=this.add.rectangle(39,0,20,18,0xaaa8b0);const label=this.add.text(-12,0,'USB',{fontFamily:'Space Mono',fontSize:'12px',color:'#17111e'}).setOrigin(.5);this.usb=this.add.container(520,GROUND_Y-65,[body,plug,label]).setDepth(Depth.COLLECTIBLES);this.usbZone=this.add.zone(520,GROUND_Y-65,90,70);this.physics.add.existing(this.usbZone,true);this.physics.add.overlap(this.player,this.usbZone,()=>{if(this.progress.hasUsb)return;this.progress=collectUsb(this.progress);this.usb.destroy();this.usbZone.destroy();this.hud.flash('USB COLLECTED\nCAREER SAVED',1700);this.hud.update(this.progress);});this.tweens.add({targets:this.usb,y:'-=10',yoyo:true,repeat:-1,duration:600,ease:'Sine.inOut'});}
 private createFinish(){this.finishZone=this.add.zone(5740,480,180,260);this.physics.add.existing(this.finishZone,true);this.physics.add.overlap(this.player,this.finishZone,()=>this.finish());}
 private action(){if(this.progress.state==='intro'){this.progress=startRun(this.progress);this.intro.destroy();this.hud.flash('GET TO THE CLUB',900);return}if(this.progress.state==='running')this.player.jump();else if(this.progress.state==='gameOver')this.scene.restart();}
 private hitObstacle(){if(this.invulnerable||this.progress.state!=='running')return;this.invulnerable=true;this.progress=applyObstacle(this.progress);this.hud.update(this.progress);this.hud.flash('-5 SECONDS');this.player.setTintFill(0xff3d66);this.cameras.main.shake(160,.008);this.time.delayedCall(1000,()=>{this.invulnerable=false;this.player.clearTint()});if(this.progress.seconds===0)this.gameOver();}
 private finish(){if(this.progress.state!=='running')return;if(!this.progress.hasUsb){this.hud.flash('YOU FORGOT THE USB',1800);return}this.progress=tryFinish(this.progress);this.player.halt();this.physics.pause();this.hud.flash(`YOU MADE IT\nFINAL SCORE  ${this.progress.score}`,1800);this.time.delayedCall(2000,()=>this.scene.start('RhythmScene',{score:this.progress.score}));}
 private gameOver(){if(this.progress.state!=='gameOver')this.progress={...this.progress,state:'gameOver'};this.player.halt();this.physics.pause();const bg=this.add.rectangle(DESIGN_WIDTH/2,DESIGN_HEIGHT/2,680,240,0x0a0710,.94).setScrollFactor(0).setDepth(Depth.UI);const tx=this.add.text(DESIGN_WIDTH/2,DESIGN_HEIGHT/2,'YOU MISSED YOUR SET\n\nPRESS SPACE OR TAP TO RESTART',{fontFamily:'Archivo Black',fontSize:'34px',color:'#ff5b49',align:'center'}).setOrigin(.5).setScrollFactor(0).setDepth(Depth.UI);void bg;void tx;}
 update(_time:number,delta:number){if(Phaser.Input.Keyboard.JustDown(this.space)||Phaser.Input.Keyboard.JustDown(this.keys.up))this.action();if(this.progress.state!=='running')return;this.player.run();this.progress=tickTimer(this.progress,delta/1000);this.hud.update(this.progress);if(this.progress.state==='gameOver')this.gameOver();}
}
