import { relative, sep } from 'node:path';
import type { Plugin } from 'vite';
import { discoverCharacters, PLAYERS_DIRECTORY } from './characterDiscovery';

/**
 * Serves the discovered character manifest as a virtual module, so no
 * generated file is committed and the working tree never goes dirty just
 * because a character folder changed.
 *
 * Runs for both `serve` and `build`: adding or removing a directory under
 * `public/assets/players` is picked up by a production build with no source
 * edit, and in dev a change under that directory invalidates the module and
 * triggers a reload.
 */
export const CHARACTER_MANIFEST_MODULE = 'virtual:holyberg-characters';
const RESOLVED_ID = `\0${CHARACTER_MANIFEST_MODULE}`;

export function characterManifestPlugin(): Plugin {
  let root = process.cwd();

  return {
    name: 'holyberg-character-manifest',
    configResolved(config) {
      root = config.root;
    },
    resolveId(id) {
      return id === CHARACTER_MANIFEST_MODULE ? RESOLVED_ID : undefined;
    },
    async load(id) {
      if (id !== RESOLVED_ID) return undefined;
      const { definitions, warnings } = await discoverCharacters(root);
      for (const warning of warnings) this.warn(warning);
      if (definitions.length === 0) {
        this.warn(`no character folders found under ${PLAYERS_DIRECTORY}`);
      }
      // JSON.stringify keeps the emitted module deterministic; the manifest
      // is already sorted by id upstream.
      return [
        '// Generated by holyberg-character-manifest from public/assets/players.',
        '// Not a file on disk: edit the folders, not this.',
        `export const CHARACTER_MANIFEST = ${JSON.stringify(definitions, null, 2)};`,
        'export default CHARACTER_MANIFEST;',
      ].join('\n');
    },
    configureServer(server) {
      const playersPrefix = `${PLAYERS_DIRECTORY.split('/').join(sep)}${sep}`;
      const invalidate = (file: string): void => {
        const relativePath = relative(root, file);
        if (!relativePath.startsWith(playersPrefix)) return;
        const module = server.moduleGraph.getModuleById(RESOLVED_ID);
        if (module) server.moduleGraph.invalidateModule(module);
        server.ws.send({ type: 'full-reload' });
        server.config.logger.info(
          `[characters] ${relativePath} changed, character manifest rebuilt`,
        );
      };
      server.watcher.on('add', invalidate);
      server.watcher.on('unlink', invalidate);
      server.watcher.on('change', invalidate);
      // Vite does not watch `public/` for module graph purposes by default.
      server.watcher.add(`${root}${sep}${PLAYERS_DIRECTORY.split('/').join(sep)}`);
    },
  };
}
